---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  attributes:
    java:
      oracle:
        accept_oracle_download_terms: true

platforms:
  - name: centos-6.6

suites:
  - name: server
    run_list:
      - recipe[crowd::server]
