---
provisioner:
  name: chef_solo
  attributes:
    java:
      oracle:
        accept_oracle_download_terms: true

suites:
  - name: server
    run_list:
      - recipe[crowd::server]
    excludes:
      - centos-7
